FROM adoptopenjdk/openjdk11
RUN echo "CONFIGURE APP ENVIRONMENTS.............."
ENV APP_HOME /app
ENV LOG_FILE_PATH /log
ENV JAR_FILE_NAME wod-0.0.1-SNAPSHOT.jar
ENV APP_PATH $APP_HOME/$JAR_FILE_NAME
RUN mkdir $APP_HOME

RUN echo "SET LOG FILE PATH TO VOLUME............."
VOLUME $LOG_FILE_PATH

RUN echo "RUN APPLICATION......................."
ADD /build/libs/$JAR_FILE_NAME $APP_PATH
EXPOSE 8080
ENTRYPOINT java -jar  $APP_PATH